version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: bachata_feedback
      MYSQL_USER: bachata_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  api:
    build:
      context: .
      dockerfile: BachataFeedback.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=bachata_feedback;User=bachata_user;Password=${MYSQL_PASSWORD};AllowUserVariables=true;UseAffectedRows=false;
      - JwtSettings__Secret=${JWT_SECRET}
      - JwtSettings__Issuer=${DOMAIN}
      - JwtSettings__Audience=${DOMAIN}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=https://${DOMAIN}/api
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mysql_data: