version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: bachata_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: bachata_feedback
      MYSQL_USER: bachata_user
      MYSQL_PASSWORD: bachata_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  minio:
    image: minio/minio:latest
    container_name: bachata_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadminpass
    ports:
      - "9000:9000"   # S3 API (локально)
      - "9001:9001"   # Web-консоль (локально)
    volumes:
      - minio_data:/data
    restart: unless-stopped

  clamav:
    image: clamav/clamav:stable
    container_name: bachata_clamav
    ports:
      - "3310:3310"   # TCP clamd (локально)
    restart: unless-stopped

  bachatafeedback.api:
    image: ${DOCKER_REGISTRY-}bachatafeedbackapi
    container_name: bachata_api
    build:
      context: .
      dockerfile: BachataFeedback.Api/Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      mysql:
        condition: service_healthy
      minio:
        condition: service_started
      clamav:
        condition: service_started
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=bachata_feedback;User=bachata_user;Password=bachata_pass;AllowUserVariables=true;UseAffectedRows=false;
      # Storage (MinIO)
      - Storage__Provider=Minio
      - Storage__Endpoint=minio:9000
      - Storage__AccessKey=minioadmin
      - Storage__SecretKey=minioadminpass
      - Storage__Bucket=bf-media
      - Storage__UseSSL=false
      # Antivirus (ClamAV)
      - Antivirus__ClamAV__Host=clamav
      - Antivirus__ClamAV__Port=3310
      # Upload limits
      - Uploads__MaxSizeMb=10
      - Uploads__AllowedTypes__0=image/jpeg
      - Uploads__AllowedTypes__1=image/png
      - Uploads__AllowedTypes__2=image/webp
    restart: unless-stopped

volumes:
  mysql_data:
  minio_data: